# Generated by Django 4.2.9 on 2024-02-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_approved_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_on']},
        ),
    ]
